import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#faf8ff',
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 12,
  },
  wideContent: {
    maxWidth: 480,
    alignSelf: 'center',
    width: '100%',
  },

  /* 1. Subheader */
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 2,
  },
  headerLeft: {
    flexDirection: 'column',
  },
  headingTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#131b2e',
    letterSpacing: -0.3,
  },
  dayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#eaedff',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  dayBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#3d4947',
  },

  /* 2. Bento 1: Daily Readiness & Progress Gauge */
  readinessCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#eaedff',
    shadowColor: '#00685f',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
    gap: 12,
  },
  readinessTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  gaugeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  svgRingWrapper: {
    width: 56,
    height: 56,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeInnerLabel: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugePercent: {
    fontSize: 14,
    fontWeight: '800',
    color: '#131b2e',
    lineHeight: 16,
  },
  gaugeStatus: {
    fontSize: 8.5,
    fontWeight: '800',
    color: '#008378',
    letterSpacing: 0.2,
  },
  readinessInfo: {
    flexDirection: 'column',
    gap: 4,
  },
  stateTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  stateTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#131b2e',
  },
  metricPillsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metricPillGreen: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#f0fdf4',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#bbf7d0',
  },
  metricPillGreenText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#15803d',
  },
  metricPillTeal: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#f0fdfa',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  metricPillTealText: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#0f766e',
  },
  questsSummary: {
    alignItems: 'flex-end',
  },
  questsBadge: {
    backgroundColor: '#ffedd5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#fed7aa',
  },
  questsBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#ea580c',
  },
  syncBtnPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  syncBtnText: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#0f766e',
  },
  xpGainedSub: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748b',
    marginTop: 3,
  },

  /* Micro-Gauge Strip */
  microGaugeStrip: {
    flexDirection: 'row',
    gap: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(234, 237, 255, 0.8)',
  },
  microGaugeCol: {
    flex: 1,
    backgroundColor: 'rgba(242, 243, 255, 0.7)',
    borderRadius: 10,
    padding: 8,
  },
  microGaugeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  microGaugeTitle: {
    fontSize: 9.5,
    fontWeight: '700',
    color: '#64748b',
    letterSpacing: 0.3,
  },
  microGaugeHeaderRight: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#64748b',
  },
  microGaugeVal: {
    fontSize: 12,
    fontWeight: '900',
    color: '#131b2e',
    marginVertical: 1,
  },
  progressBarTrack: {
    width: '100%',
    height: 5,
    backgroundColor: '#e2e8f0',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 4,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 999,
  },

  /* 3. Priority Workout Card */
  workoutCard: {
    borderRadius: 16,
    padding: 14,
    borderWidth: 2,
    borderColor: '#14b8a6',
    shadowColor: '#14b8a6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 3,
    gap: 12,
  },
  workoutCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  workoutInfoLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  workoutIconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#065f46',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 0,
  },
  workoutTitles: {
    flex: 1,
  },
  workoutBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  priorityPill: {
    backgroundColor: '#ffedd5',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  priorityPillText: {
    fontSize: 9.5,
    fontWeight: '800',
    color: '#ea580c',
    letterSpacing: 0.4,
  },
  durationBullet: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
  },
  workoutName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#131b2e',
    lineHeight: 20,
  },
  xpRewardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  xpRewardText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#0f766e',
  },
  highlightsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    width: '100%',
  },
  highlightPill: {
    flex: 1,
    flexShrink: 1,
    overflow: 'hidden',
    backgroundColor: '#f2f3ff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eaedff',
  },
  highlightPillTeal: {
    borderColor: '#ccfbf1',
    backgroundColor: '#f0fdfa',
  },
  highlightText: {
    fontSize: 11.5,
    fontWeight: '600',
    color: '#3d4947',
    lineHeight: 16,
  },
  clickableDescriptionBox: {
    backgroundColor: '#f2f3ff',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#eaedff',
    gap: 8,
  },
  descTextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },

  startWorkoutTouch: {
    width: '100%',
    borderRadius: 12,
    borderBottomWidth: 3,
    borderBottomColor: '#065f46',
    overflow: 'hidden',
  },
  startWorkoutGradient: {
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  startWorkoutText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#ffffff',
  },

  /* 5. Daily Habits / Quests Grid */
  habitsSection: {
    gap: 8,
    marginTop: 2,
  },
  habitsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
  },
  habitsTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#131b2e',
    letterSpacing: 0.4,
  },
  habitsSub: {
    fontSize: 11,
    fontWeight: '700',
    color: '#00685f',
  },
  habitsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  habitCard: {
    width: '47.5%',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#eaedff',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  habitContent: {
    flex: 1,
  },
  habitTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  habitIconBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  habitXpBadge: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  habitXpText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#b45309',
  },
  habitCardTitle: {
    fontSize: 12.5,
    fontWeight: '800',
    color: '#131b2e',
    lineHeight: 16,
  },
  habitCardSub: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#64748b',
    marginTop: 2,
  },
  stepsStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  stepsCount: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#64748b',
  },
  stepsPercent: {
    fontSize: 10.5,
    fontWeight: '800',
    color: '#059669',
  },
  habitActionBtn: {
    marginTop: 10,
    width: '100%',
    paddingVertical: 5,
    backgroundColor: '#f2f3ff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eaedff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  habitActionBtnActive: {
    backgroundColor: '#dcfce7',
    borderColor: '#bbf7d0',
  },
  habitActionBtnActiveOrange: {
    backgroundColor: '#ffedd5',
    borderColor: '#fed7aa',
  },
  habitActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#0f766e',
  },
  notTodayBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#e6f7f5',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#b2ece4',
    gap: 10,
  },
  notTodayBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  notTodayBannerText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#004c44',
  },
  switchTodayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00685f',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  switchTodayBtnText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#ffffff',
  },
  disabledPastBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecfdf5',
    borderWidth: 1.5,
    borderColor: '#a7f3d0',
    borderRadius: 12,
    paddingVertical: 12,
    width: '100%',
  },
  disabledPastText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#065f46',
  },
  disabledFutureBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingVertical: 12,
    width: '100%',
  },
  disabledFutureText: {
    fontSize: 13.5,
    fontWeight: '800',
    color: '#64748b',
  },
  jumpTodaySecondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f0fdfa',
    borderWidth: 1,
    borderColor: '#99f6e4',
    borderRadius: 10,
    paddingVertical: 9,
    width: '100%',
  },
  jumpTodaySecondaryText: {
    fontSize: 12.5,
    fontWeight: '700',
    color: '#00685f',
  },
});


export default styles;
