import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../../theme';

const styles = StyleSheet.create({
  addMealActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    borderRadius: 14,
    marginTop: 8,
  },
  addMealActionBtnText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  loggedMealsCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    gap: 12,
  },
  loggedMealsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  loggedMealsTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#0f172a',
  },
  loggedMealsList: {
    gap: 8,
  },
  loggedMealRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  loggedMealLeft: {
    gap: 2,
  },
  loggedMealName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  loggedMealSub: {
    fontSize: 12,
    color: '#64748b',
  },
  loggedMealCalBadge: {
    backgroundColor: '#fef3c7',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  loggedMealCalText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#d97706',
  },
  logRecipeDetailBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 20,
  },
  logRecipeDetailBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  addMealModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  addMealModalCard: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '85%',
  },
  addMealModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  addMealModalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  addMealTabGroup: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  addMealTabBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: 'center',
    borderRadius: 10,
  },
  addMealTabBtnActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  addMealTabText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#64748b',
  },
  addMealTabTextActive: {
    color: '#0f172a',
  },
  appRecipeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  appRecipeThumb: {
    width: 48,
    height: 48,
    borderRadius: 12,
  },
  appRecipeTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#0f172a',
  },
  appRecipeSub: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 2,
  },
  logAppRecipeChipBtn: {
    backgroundColor: '#ccfbf1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  logAppRecipeChipText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#0f766e',
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 6,
    marginTop: 10,
  },
  customInput: {
    height: 44,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    fontSize: 14,
    color: '#0f172a',
    marginBottom: 10,
  },
  submitCustomBtn: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 20,
    marginBottom: 10,
  },
  submitCustomBtnText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '800',
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 16,
    gap: 16,
  },
  headerSection: {
    gap: 6,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginTop: 2,
  },
  mainTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.4,
  },
  targetSub: {
    fontSize: 11,
    fontWeight: '600',
    color: '#3d4947',
  },
  bentoCard: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#131b2e',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    gap: 12,
  },
  bentoTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  gaugeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  gaugeWrap: {
    position: 'relative',
    width: 64,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeCenterText: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugePercent: {
    fontSize: 12,
    fontWeight: '900',
    color: '#00685f',
  },
  calInfoGroup: {
    gap: 2,
  },
  calNumbersRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  calIntake: {
    fontSize: 18,
    fontWeight: '900',
    color: '#131b2e',
  },
  calTarget: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
  },
  calLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  calLeftText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#ea580c',
  },
  hydrationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#c9e6ff',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#89ceff',
  },
  hydrationBtnSuccess: {
    backgroundColor: '#89f5e7',
    borderBottomColor: '#6bd8cb',
  },
  hydrationText: {
    fontSize: 11,
    fontWeight: '900',
    color: '#00628d',
  },
  hydrationTextSuccess: {
    color: '#00685f',
  },
  hydrationAddChip: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 2,
  },
  hydrationAddText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#00628d',
  },
  macroGrid: {
    flexDirection: 'row',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#f2f3ff',
    paddingTop: 10,
  },
  macroCol: {
    flex: 1,
    backgroundColor: '#f2f3ff',
    borderRadius: 12,
    padding: 8,
    gap: 4,
  },
  macroHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  macroLabel: {
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  macroVal: {
    fontSize: 13,
    fontWeight: '900',
    color: '#131b2e',
  },
  macroMax: {
    fontSize: 9,
    fontWeight: '500',
    color: '#64748b',
  },
  progressBarBg: {
    height: 5,
    backgroundColor: '#e2e7ff',
    borderRadius: 3,
    overflow: 'hidden',
    marginTop: 2,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 3,
  },
  sectionWrap: {
    gap: 10,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionHeading: {
    fontSize: 16,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.3,
  },
  recipeCountBadge: {
    backgroundColor: '#e2e7ff',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  recipeCountText: {
    fontSize: 10,
    fontWeight: '800',
    color: '#00685f',
  },
  dietFilterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: 2,
  },
  dietFilterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  dietFilterBtnActiveAll: {
    backgroundColor: '#131b2e',
    borderColor: '#131b2e',
  },
  dietFilterBtnActiveVeg: {
    backgroundColor: '#00685f',
    borderColor: '#00685f',
  },
  dietFilterBtnActiveNonVeg: {
    backgroundColor: '#ea580c',
    borderColor: '#ea580c',
  },
  dietFilterText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  dietFilterTextActive: {
    color: '#ffffff',
  },
  seeAllBtn: {
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  seeAllLink: {
    fontSize: 12,
    fontWeight: '800',
    color: '#00685f',
  },
  tapTipText: {
    fontSize: 11,
    color: '#64748b',
    fontWeight: '500',
    marginTop: -4,
  },
  recipesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  recipeCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    padding: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
    gap: 6,
  },
  recipeImageWrap: {
    position: 'relative',
    height: 96,
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#e2e7ff',
  },
  recipeImage: {
    width: '100%',
    height: '100%',
  },
  recipeTagBadge: {
    position: 'absolute',
    top: 6,
    left: 6,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  dietBadge: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
  },
  vegBadgeBg: {
    backgroundColor: '#00685f',
  },
  nonVegBadgeBg: {
    backgroundColor: '#ea580c',
  },
  dietBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#ffffff',
  },
  tagText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#ffffff',
  },
  timeTag: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  timeTagText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#131b2e',
  },
  recipeTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#131b2e',
  },
  recipeMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    flexWrap: 'wrap',
  },
  macroBadgeOrange: {
    backgroundColor: '#ffdbca',
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  macroBadgeOrangeText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#9d4300',
  },
  macroBadgeTeal: {
    backgroundColor: '#89f5e7',
    paddingHorizontal: 5,
    paddingVertical: 1.5,
    borderRadius: 6,
  },
  macroBadgeTealText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#00685f',
  },
  recipeCalories: {
    fontSize: 10,
    fontWeight: '600',
    color: '#64748b',
    marginLeft: 'auto',
  },
  modalSafeArea: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingTop: Platform.OS === 'android' ? 24 : 0,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalHeaderTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#131b2e',
    flex: 1,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  modalScrollContent: {
    paddingBottom: 16,
  },
  modalImageContainer: {
    position: 'relative',
    height: 220,
    width: '100%',
    backgroundColor: '#e2e7ff',
  },
  modalHeroImage: {
    width: '100%',
    height: '100%',
  },
  modalTagBadge: {
    position: 'absolute',
    bottom: 12,
    left: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modalDietBadge: {
    position: 'absolute',
    bottom: 12,
    left: 110,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modalTagText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  modalDietText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  modalBodyGroup: {
    padding: 18,
    gap: 16,
  },
  modalRecipeTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.4,
  },
  modalSummary: {
    fontSize: 13,
    color: '#475569',
    lineHeight: 20,
    fontWeight: '500',
  },
  modalMacroRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#f8fafc',
    borderRadius: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalMacroCol: {
    alignItems: 'center',
    gap: 2,
  },
  modalMacroVal: {
    fontSize: 17,
    fontWeight: '900',
    color: '#131b2e',
  },
  modalMacroLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: '#64748b',
    letterSpacing: 0.5,
  },
  modalMacroDivider: {
    width: 1,
    height: 28,
    backgroundColor: '#e2e8f0',
  },
  coachTipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fffbeb',
    borderRadius: 16,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  coachTipTextWrap: {
    flex: 1,
    gap: 2,
  },
  coachTipTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: '#92400e',
  },
  coachTipText: {
    fontSize: 12,
    color: '#78350f',
    lineHeight: 18,
    fontWeight: '500',
  },
  detailSectionWrap: {
    gap: 10,
    marginTop: 4,
  },
  sectionIconTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailSectionTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#131b2e',
  },
  ingredientList: {
    backgroundColor: '#f8fafc',
    borderRadius: 16,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  bulletDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#00685f',
  },
  ingredientText: {
    fontSize: 13,
    color: '#334155',
    fontWeight: '600',
    flex: 1,
  },
  stepsList: {
    gap: 12,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: '#f8fafc',
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  stepNumberCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#00685f',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 1,
  },
  stepNumberText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#ffffff',
  },
  stepText: {
    flex: 1,
    fontSize: 13,
    color: '#334155',
    lineHeight: 19,
    fontWeight: '500',
  },
  customRecipeCard: {
    width: '48%',
    backgroundColor: '#f0fdfa',
    borderRadius: 16,
    padding: 10,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#00685f',
    gap: 8,
  },
  customRecipeImageWrap: {
    height: 110,
    borderRadius: 12,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  customFieldHeading: {
    fontSize: 11,
    fontWeight: '900',
    color: '#00685f',
    letterSpacing: 0.8,
    marginTop: 4,
  },
  customTitleInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#00685f',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '700',
    color: '#131b2e',
  },
  modalMacroColInput: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  macroInputField: {
    fontSize: 18,
    fontWeight: '900',
    color: '#131b2e',
    textAlign: 'center',
    paddingVertical: 4,
    minWidth: 50,
    borderBottomWidth: 1.5,
    borderBottomColor: '#cbd5e1',
  },
  customNotesInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 14,
    padding: 12,
    fontSize: 13,
    color: '#131b2e',
    textAlignVertical: 'top',
    height: 80,
  },

});

export default styles;
