import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF9F6',
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 20) : 0,
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  progressContainer: {
    marginBottom: 8,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: '#e2e8f0',
    borderRadius: 3,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#0d9488',
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    textAlign: 'right',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  stepContainer: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  stepSubtitle: {
    fontSize: 14,
    color: '#64748b',
    fontWeight: '500',
    marginBottom: 20,
  },
  questionLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#334155',
    marginTop: 24,
    marginBottom: 12,
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  optionCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  optionCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  optionCardSelected: {
    borderColor: '#0d9488',
    backgroundColor: '#f0fdfa',
  },
  optionText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#475569',
  },
  optionTextSelected: {
    color: '#0f766e',
    fontWeight: '700',
  },
  optionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  optionChip: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  optionChipSelected: {
    borderColor: '#0d9488',
    backgroundColor: '#f0fdfa',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    paddingHorizontal: 12,
    height: 50,
  },
  inputIcon: {
    marginRight: 8,
  },
  inputField: {
    flex: 1,
    height: 48,
    fontSize: 14,
    fontWeight: '600',
    color: '#0f172a',
    paddingVertical: 0,
  },
  dateInputs: {
    flex: 1,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateYearInput: {
    flex: 0,
    width: 56,
    textAlign: 'center',
  },
  dateShortInput: {
    flex: 0,
    width: 34,
    textAlign: 'center',
  },
  dateSeparator: {
    color: '#64748b',
    fontSize: 16,
    fontWeight: '600',
  },
  daysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  dayCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayCircleSelected: {
    borderColor: '#0d9488',
    backgroundColor: '#0d9488',
  },
  dayText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#64748b',
  },
  dayTextSelected: {
    color: '#ffffff',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#0d9488',
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#0d9488',
    borderColor: '#0d9488',
  },
  summaryBox: {
    backgroundColor: '#f0fdfa',
    borderRadius: 20,
    padding: 20,
    marginTop: 30,
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  summaryTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f766e',
    marginBottom: 8,
  },
  summaryText: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 20,
  },
  notSureBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
    gap: 10,
  },
  notSureBtnActive: {
    borderColor: '#0d9488',
    backgroundColor: '#f0fdfa',
  },
  notSureText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#64748b',
  },
  notSureTextActive: {
    color: '#0f766e',
    fontWeight: '700',
  },
  notSureCard: {
    backgroundColor: '#f0fdfa',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#99f6e4',
    alignItems: 'center',
    gap: 6,
    marginVertical: 10,
  },
  notSureCardEmoji: {
    fontSize: 28,
  },
  notSureCardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f766e',
  },
  notSureCardText: {
    fontSize: 13,
    color: '#334155',
    textAlign: 'center',
    lineHeight: 18,
  },
  validationErrorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    borderColor: '#fecaca',
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginHorizontal: 20,
    marginBottom: 10,
    gap: 8,
  },
  validationErrorText: {
    flex: 1,
    fontSize: 12,
    color: '#b91c1c',
    fontWeight: '600',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'android' ? 24 : 20,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  navBtn: {
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  navBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#64748b',
  },
  nextBtn: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#0d9488',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 3,
  },
  nextGradient: {
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  nextBtnText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#ffffff',
  },
});

export default styles;
