import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme';

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  adjustModalCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#0f172a',
  },
  modalSub: {
    fontSize: 13,
    color: '#64748b',
    marginBottom: 12,
    lineHeight: 18,
  },
  eventOptionsList: {
    gap: 8,
    marginBottom: 12,
  },
  eventOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8fafc',
    padding: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  eventOptionCardSelected: {
    backgroundColor: '#f0fdfa',
    borderColor: COLORS.primary,
  },
  eventOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  eventOptionIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventOptionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  eventOptionDate: {
    fontSize: 11,
    color: '#64748b',
  },
  modalInputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 6,
    marginTop: 10,
  },
  modalInput: {
    height: 44,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    fontSize: 15,
    color: '#0f172a',
    marginBottom: 16,
  },
  modalBtnRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 20,
  },
  modalCancelBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
  },
  modalCancelBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#64748b',
  },
  modalSaveBtn: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: COLORS.primary,
  },
  modalSaveBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
  },
  container: {
    flex: 1,
    backgroundColor: '#faf8ff',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  progressHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 4,
    gap: 8,
  },
  progressTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  stepText: {
    fontSize: 12,
    fontWeight: '900',
    color: COLORS.primary,
    letterSpacing: 0.5,
  },
  readyPct: {
    fontSize: 12,
    fontWeight: '700',
    color: '#6d7a77',
  },
  progressBarRow: {
    flexDirection: 'row',
    gap: 6,
  },
  progressSegment: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#dae2fd',
  },
  segmentFilled: {
    backgroundColor: COLORS.primary,
  },
  segmentFilledActive: {
    backgroundColor: COLORS.primary,
    opacity: 0.8,
  },
  targetEventCard: {
    marginHorizontal: 16,
    marginTop: 8,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 14,
    borderWidth: 2,
    borderColor: '#eaedff',
    borderBottomWidth: 4,
    borderBottomColor: '#dae2fd',
    elevation: 2,
    gap: 10,
  },
  targetEventTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  targetEventLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  targetEventIconBox: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#89f5e7',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  targetEventTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  targetEventLabel: {
    fontSize: 9,
    fontWeight: '900',
    color: '#6d7a77',
    letterSpacing: 0.5,
  },
  targetEventTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.2,
  },
  targetEventDate: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6d7a77',
  },
  adjustBtn: {
    backgroundColor: '#eaedff',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 14,
    flexShrink: 0,
  },
  adjustBtnText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.primary,
  },
  targetRampPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f6f7ff',
    padding: 10,
    borderRadius: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: '#eaedff',
  },
  trendingBox: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#ffdbca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rampTextWrap: {
    flex: 1,
    gap: 1,
  },
  rampHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  rampWeeks: {
    fontSize: 12,
    fontWeight: '850',
    color: '#783200',
  },
  dotSeparator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#783200',
    opacity: 0.5,
  },
  rampLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ea580c',
  },
  rampSub: {
    fontSize: 10.5,
    fontWeight: '600',
    color: '#6d7a77',
    lineHeight: 14,
  },
  topHeader: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  coachAvatarWrapper: {
    width: 42,
    height: 42,
    borderRadius: 21,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#6bd8cb',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  coachAvatar: {
    width: '100%',
    height: '100%',
  },
  monthBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 2,
  },
  monthBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.primary,
    letterSpacing: 0.6,
  },
  screenTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.5,
  },
  viewToggleGroup: {
    flexDirection: 'row',
    backgroundColor: '#e2e7ff',
    padding: 3,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  toggleBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  toggleBtnActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  toggleBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#3d4947',
  },
  toggleBtnTextActive: {
    color: COLORS.primary,
    fontWeight: '900',
  },
  calendarCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 14,
    borderWidth: 2,
    borderColor: '#eaedff',
    borderBottomWidth: 4,
    borderBottomColor: '#dae2fd',
    elevation: 2,
  },
  calendarCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 4,
    gap: 8,
  },
  weekThemeRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
    marginRight: 6,
  },
  weekThemeText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    color: '#131b2e',
  },
  weekDateBadge: {
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    flexShrink: 0,
  },
  weekDateRange: {
    fontSize: 11.5,
    fontWeight: '700',
    color: '#64748b',
    flexShrink: 0,
  },
  daysGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 4,
  },
  dayCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 2,
    borderRadius: 14,
    backgroundColor: '#f2f3ff',
    borderWidth: 1,
    borderColor: '#eaedff',
  },
  dayCardSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#f0fdfa',
  },
  dayCardToday: {
    backgroundColor: COLORS.primary,
    borderColor: '#89f5e7',
    borderWidth: 2,
    borderBottomWidth: 4,
    borderBottomColor: '#004c44',
  },
  dayLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6d7a77',
  },
  dayLabelToday: {
    color: '#89f5e7',
    fontWeight: '900',
  },
  dayNumber: {
    fontSize: 15,
    fontWeight: '900',
    color: '#131b2e',
    marginTop: 2,
    marginBottom: 6,
  },
  dayNumberToday: {
    color: '#ffffff',
  },
  dayStatusCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthCalendarCard: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 16,
    borderWidth: 2,
    borderColor: '#eaedff',
    borderBottomWidth: 4,
    borderBottomColor: '#dae2fd',
    elevation: 2,
  },
  monthCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  monthHeaderTitleWrap: {
    gap: 2,
  },
  monthNameTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#131b2e',
    letterSpacing: -0.3,
  },
  monthSubTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6d7a77',
  },
  monthStatBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fff0e5',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffd8be',
  },
  monthStatText: {
    fontSize: 11,
    fontWeight: '850',
    color: '#ea580c',
  },
  monthDOWRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    gap: 6,
  },
  monthDOWText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 10,
    fontWeight: '800',
    color: '#6d7a77',
    letterSpacing: 0.3,
  },
  monthWeeksContainer: {
    gap: 6,
  },
  monthWeekRow: {
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'space-between',
  },
  monthOtherMonthCell: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: '#fafbff',
    borderWidth: 1,
    borderColor: '#f0f2f8',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 6,
    opacity: 0.35,
  },
  monthOtherMonthNum: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
  },
  monthDayCell: {
    flex: 1,
    minHeight: 52,
    borderRadius: 12,
    backgroundColor: '#f8f9ff',
    borderWidth: 1.5,
    borderColor: '#eaedff',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 5,
    paddingHorizontal: 2,
  },
  monthDayCellToday: {
    backgroundColor: COLORS.primary,
    borderColor: '#89f5e7',
    borderWidth: 2,
    borderBottomWidth: 3,
    borderBottomColor: '#004c44',
  },
  monthDayCellSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#f0fdfa',
    borderWidth: 2,
  },
  monthDayNum: {
    fontSize: 12,
    fontWeight: '800',
    color: '#131b2e',
  },
  monthDayNumToday: {
    color: '#ffffff',
    fontWeight: '900',
  },
  monthDayNumSelected: {
    color: COLORS.primary,
    fontWeight: '900',
  },
  monthDayDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthDayEmptyDot: {
    width: 20,
    height: 20,
  },
  todaySection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  todayHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  todayTitleLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  livePing: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
  },
  todaySectionTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#131b2e',
  },
  todayPill: {
    backgroundColor: 'rgba(107, 216, 203, 0.3)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  todayPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.primary,
  },
  workoutCardWrapper: {
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#00685f',
    borderBottomWidth: 4,
    borderBottomColor: '#005049',
    elevation: 4,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  workoutCard: {
    padding: 16,
  },
  workoutMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  workoutIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  workoutTextWrap: {
    flex: 1,
  },
  workoutTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#00201d',
    letterSpacing: -0.3,
  },
  workoutSubtitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#003833',
    marginTop: 2,
  },
  metricsGrid: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 14,
  },
  metricCol: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 14,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 2,
  },
  metricLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#6d7a77',
  },
  metricVal: {
    fontSize: 15,
    fontWeight: '900',
    color: COLORS.primary,
    marginTop: 2,
  },
  equipmentBadgesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 12,
  },
  gearPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
  },
  gearPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#131b2e',
  },
  startWorkoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 16,
    gap: 8,
    borderBottomWidth: 3,
    borderBottomColor: '#003833',
    elevation: 3,
  },
  startWorkoutBtnText: {
    fontSize: 16,
    fontWeight: '900',
    color: '#ffffff',
    letterSpacing: -0.2,
  },
  disabledPastBtn: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1.5,
    borderColor: '#a7f3d0',
    borderBottomColor: '#6ee7b7',
  },
  disabledPastBtnText: {
    color: '#065f46',
    fontSize: 15,
    fontWeight: '800',
  },
  lockedBtnContainer: {
    gap: 8,
    width: '100%',
    marginTop: 16,
  },
  disabledFutureBtn: {
    marginTop: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.65)',
    borderWidth: 1.5,
    borderColor: '#cbd5e1',
    borderBottomColor: '#94a3b8',
  },
  disabledFutureBtnText: {
    color: '#475569',
    fontSize: 15,
    fontWeight: '800',
  },
  jumpToTodayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.primary,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  jumpToTodayBtnText: {
    fontSize: 13,
    fontWeight: '800',
    color: COLORS.primary,
  },
  adaptSection: {
    paddingHorizontal: 16,
    marginTop: 20,
  },
  adaptCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 16,
    borderWidth: 2,
    borderColor: '#eaedff',
    borderBottomWidth: 4,
    borderBottomColor: '#dae2fd',
    elevation: 2,
  },
  adaptHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 14,
  },
  adaptIconBox: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#ffdbca',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adaptHeaderTextWrap: {
    flex: 1,
  },
  adaptTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: '#131b2e',
  },
  adaptSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6d7a77',
    marginTop: 1,
  },
  adaptButtonsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  adaptOptionBtn: {
    width: '48.5%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f2f3ff',
    borderWidth: 1.5,
    borderColor: '#eaedff',
    borderRadius: 16,
    padding: 12,
  },
  adaptOptionBtnActive: {
    borderColor: COLORS.primary,
    backgroundColor: '#f0fdfa',
  },
  adaptOptionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#131b2e',
  },
  adaptOptionSub: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6d7a77',
    marginTop: 1,
  },
  promiseFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#eaedff',
  },
  promiseText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#3d4947',
    flex: 1,
    lineHeight: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#131b2e',
  },
  modalSub: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 16,
  },
  eventOptionsList: {
    gap: 10,
  },
  eventOptionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 16,
    backgroundColor: '#f8fafc',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  eventOptionCardSelected: {
    borderColor: COLORS.primary,
    backgroundColor: '#f0fdfa',
  },
  eventOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  eventOptionIconBox: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventOptionTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#131b2e',
  },
  eventOptionDate: {
    fontSize: 11,
    fontWeight: '600',
    color: '#64748b',
    marginTop: 2,
  },
});

export default styles;
